=== Manavkumar2899/PWJS-MyWork/XML/external.dtd
<!ELEMENT aptech (employee+)>
<!ELEMENT employee (id , name , email , city )>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ATTLIST city town CDATA #REQUIRED>

=== Manavkumar2899/PWJS-MyWork/XML/external.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aptech SYSTEM "external.dtd" [
<!ENTITY aptech "Aptech Shahrah-e-faisal">
]>

<aptech>
<employee>
<id>1</id>
<name>ali</name>
<email>ali@gmail.com</email>
<city town="saddar">Karachi &aptech; </city>
</employee>
<employee>
<id>2</id>
<name>hamza</name>
<email>hamza@gmail.com</email>
<city town="modal">Lahore &aptech; </city>
</employee>
</aptech>
